export const FETCH_TWITCH_DATA = "FETCH_TWITCH_DATA";
export const FETCH_TWITCH_METADATA = "FETCH_TWITCH_METADATA";
export const FETCH_STATS_DATA = "FETCH_STATS_DATA";
export const FETCH_STATS_ERROR = "FETCH_STATS_ERROR";
export const FETCH_STATS_INIT = "FETCH_STATS_INIT";
export const FETCH_STATS_DONE = "FETCH_STATS_DONE";
export const FILTER_STREAM = "FILTER_STREAM";
